### ISSUE TITLE
Caching Dependencies to speed up workflows

### ISSUE THREAD

**Issue by jongwooo** [fosslight/fosslight#605]
**Is your feature request related to a problem? Please describe.**
Jobs on GitHub-hosted runners start in a clean virtual environment and **must download dependencies each time**, causing increased network utilization, longer runtime, and increased cost. To help speed up the time it takes to recreate files like dependencies, GitHub can cache files that frequently use in workflows.

**Describe the solution you'd like**
Java projects can run faster on GitHub Actions by enabling dependency caching on the [setup-java](https://github.com/actions/setup-java) action. `setup-java` supports caching for both Gradle and Maven projects.

The following example enables caching for a Java project with Gradle:

```yaml
steps:
- uses: actions/checkout@v3
- uses: actions/setup-java@v3
  with:
    java-version: '11'
    distribution: 'temurin'
    cache: 'gradle'
- run: ./gradlew build
```

The format of the used cache key is `setup-java-${{ platform }}-${{ packageManager }}-${{ fileHash }}`, where the hash is based on the following files:

gradle: `**/*.gradle*`, `**/gradle-wrapper.properties`
maven: `**/pom.xml`

**References**
[actions/setup-java#caching-packages-dependencies](https://github.com/actions/setup-java#caching-packages-dependencies)
[How to build Gradle projects with GitHub Actions](https://tomgregory.com/build-gradle-projects-with-github-actions/#5_Enable_Gradle_caching)
