### ISSUE TITLE
Separate Build and Deploy-demo from Workflow

### ISSUE THREAD

**Issue by Gseungmin** [fosslight/fosslight#948]
**Is your feature request related to a problem? Please describe.**
* The current release-publish.yml workflow has a very complex logic. 
* I am planning to abstract and refine the workflow by separating the code from the release-publish.yml workflow.
* Related Issue: https://github.com/fosslight/.github/issues/1

**Describe the solution you'd like**

* I want to separate the following code from he release-publish.yml workflow to new workflow

```
build:
  needs: update-changelog
  runs-on: ubuntu-18.04

  steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build --exclude-task test

    - name: Rename package
      run: mv build/libs/FOSSLight*.war FOSSLight.war

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./FOSSLight.war
        asset_name: FOSSLight.war
        asset_content_type: application/octet-stream

deploy-demo:
  needs: build
  runs-on: ubuntu-latest

  steps:
    - name: Sleep for 30 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '30s'

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_IP }}
        username: ${{ secrets.REMOTE_SSH_ID }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        port: ${{ secrets.REMOTE_SSH_PORT }}
        script: |
          cd /service/deploy/fosslight/
          bash /service/deploy/fosslight/deploy.sh
```

**Additional context**
* Please compare the difference between before and after
