### ISSUE TITLE
 Separate the Code Blocks below into Individual Workflows.

### ISSUE THREAD

**Issue by Gseungmin** [fosslight/fosslight#949]
**Is your feature request related to a problem? Please describe.**
* The current release-publish.yml workflow has a very complex logic.
* I am planning to abstract and refine the workflow by separating the code from the release-publish.yml workflow.
* Related Issue: https://github.com/fosslight/.github/issues/1

**Describe the solution you'd like**
" I am planning to separate the code blocks below into individual workflows.
### first code block
```
steps:
  - uses: actions/checkout@v2
    with:
      ref: ${{ matrix.ref }}

  - name: update changelog with gren
    env:
      GREN_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    run: |
      npm install github-release-notes@0.17.3
      node_modules/.bin/gren changelog --override

  - name: Commit files
    run: |
      git config --global user.email "fosslight-dev@lge.com"
      git config --global user.name "FOSSLight-dev"
      git add CHANGELOG.md
      git commit -m "Update ChangeLog on ${{ matrix.ref }} branch"

  - name: Push changes
    uses: ad-m/github-push-action@master
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      branch: ${{ matrix.ref }}
```
### second code block
```
deploy-image:
  needs: deploy-demo
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        platforms: |
          linux/arm64/v8
          linux/arm/v7
          linux/ppc64le
          linux/s390x
          linux/amd64
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/fosslight:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/fosslight:${{ github.event.release.tag_name }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
```

**Additional context**
* Please compare the difference between before and after
