### ISSUE TITLE
fetch the base-check-commit-message.yml from the .github

### ISSUE THREAD

**Issue by Gseungmin** [fosslight/fosslight#965]
**Is your feature request related to a problem? Please describe.**
* The current workflows have a significant amount of redundancy in checking commit messages.
* I am planning to abstract and refine the workflow by separating the code from repositorys in fosslight ans use separated codes in fosslight repositorys
* Related Issue: https://github.com/fosslight/.github/issues/1

**Describe the solution you'd like**
I want to fetch the base-check-commit-message.yml file from the .github repository and replace it with the following code.

```yml
check-commit-message:
  name: Check Commit Message
  runs-on: ubuntu-latest
  steps:
    - name: Get PR Commits
      id: 'get-pr-commits'
      uses: tim-actions/get-pr-commits@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Check Subject Line Length
      uses: tim-actions/commit-message-checker-with-regex@v0.3.1
      with:
        commits: ${{ steps.get-pr-commits.outputs.commits }}
        pattern: '^.{0,50}(\n.*)*$'
        error: 'Subject too long (max 50)'
    - name: Check Body Line Length
      if: ${{ success() || failure() }}
      uses: tim-actions/commit-message-checker-with-regex@v0.3.1
      with:
        commits: ${{ steps.get-pr-commits.outputs.commits }}
        pattern: '^.+(\n.{0,72})*$'
        error: 'Body line too long (max 72)'
```
