### ISSUE TITLE
Testing builds through service containers in GitHub Actions

### ISSUE THREAD

**Issue by Gseungmin** [fosslight/fosslight#985]
**Is your feature request related to a problem? Please describe.**
* Currently, build testing is being performed using Docker Compose.
* I want to change this process to use service containers. 

**Describe the solution you'd like**
* Below is the GitHub Actions code where the build is being performed using Docker Compose.
* I want to switch from Docker Compose to service containers and separate the service container logic into another yml file.
* if you are not sure, i want to remove codes about saving logs

```yml
build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up --build -d
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
      - name: Check running containers
        run: docker-compose ps
      - name: Save docker-compose logs
        run:
          docker-compose logs --no-color web > docker-compose-web.log &&
          docker-compose logs --no-color db > docker-compose-db.log &&
          docker-compose logs --no-color mail > docker-compose-mail.log
      - name: Check the site
        run: docker run --network container:fosslight_web appropriate/curl -s --retry 3 --retry-connrefused http://localhost:8180/session/login
      - name: Stop containers
        if: always()
        run: docker-compose down
      - name: Show db container log
        run: cat docker-compose-db.log
      - name: Show web container log
        run: cat docker-compose-web.log
      - name: Show mail container log
        run: cat docker-compose-mail.log
```
